name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=23.3.1
  - mlflow=2.8.1
  - hydra-core=1.3.2
  - pip:
      - wandb==0.16.0
      - hydra-joblib-launcher
